version: "3.7"

services:
  nginx:
    image: nginx:1.14.0-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  front:
    build: ../front
    restart: unless-stopped
    volumes:
      - ../front:/app
    working_dir: /app

  back:
    image: node:12.16.3-alpine3.9
    restart: unless-stopped
    volumes:
      - ../back:/app
    working_dir: /app
    command: npm run dev
  mongo:
    image: mongo:4.1.13
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: developer
    #   MONGO_INITDB_ROOT_PASSWORD: developer

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: developer
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: developer